
CREATE TABLE IF NOT EXISTS person (
                       person_id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ,

                       username varchar(255) NOT NULL UNIQUE CHECK ( length(username)>3 ),
                       password varchar(255) NOT NULL CHECK ( length(password)>3 ),
                       role varchar(255) NOT NULL CHECK ( length(role)>3 )
);

-- person-details (one-to-one)
-- (created_at, updated_at ....)  must be create together with USER
-- (name, age, email) can update via PATCH or PUT after create USER
CREATE TABLE IF NOT EXISTS details(
                        details_id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ,
                        person_id int UNIQUE REFERENCES person(person_id) ON DELETE CASCADE ,

                        name varchar(255) CHECK ( length(name)>3 ),
                        age int CHECK ( age>1 AND age<125),
                        email varchar(255) CHECK ( length(email)>3 ),

                        created_at timestamp NOT NULL,
                        updated_at timestamp NOT NULL
);

-- person-article (one-to-many)
CREATE TABLE IF NOT EXISTS article(
                        article_id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ,
                        person_id int REFERENCES person(person_id) ON DELETE CASCADE ,

                        title varchar(255) CHECK ( length(title)>3 ),
                        text text NOT NULL ,
                        likes int DEFAULT 0,

                        created_at timestamp NOT NULL,
                        updated_at timestamp NOT NULL
);

